#!/bin/sh

umask 077

port=${1-42424}

echo "$port" > /etc/pqconnect/config/pqcport

. run/bin/activate
export LD_LIBRARY_PATH=/usr/local/lib

pqconnect-keygen -c /etc/pqconnect/config -d /etc/pqconnect/keys -D
